# Generated by Django 5.2.1 on 2025-06-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoltHub', '0004_rename_capicity_chargingpoint_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='ZAR', max_length=3),
        ),
    ]
